export const Productos = [
    {
        id: 0,
        persona: 'hombre',
        categoria: 'futbol',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'Joma',
        modelo: 'maxima 23',
        color: 'Negro',
        url: '/img/zapatillas/futbol/hombre/joma-maxima-2331.jpg',
        alt: 'Zapatillas Joma de fútbol de color negro'
    },
    {
        id: 1,
        persona: 'hombre',
        categoria: 'futbol',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'Nike',
        modelo: 'mercurial vapor',
        color: 'Naranja',
        url: '/img/zapatillas/futbol/hombre/nike-mercurial-vapor.jpg',
        alt: 'Zapatillas Nike de fútbol de color naranja'
    },
    {
        id: 2,
        persona: 'hombre',
        categoria: 'futbol',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'Munich',
        modelo: 'rondo07',
        color: 'Blanco, azul y verde',
        url: '/img/zapatillas/futbol/hombre/munich-rondo07.jpg',
        alt: 'Zapatillas Munich de color blanco, azul y verde'
    },
    {
        id: 3,
        persona: 'mujer',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Lotto',
        modelo: 'stadio 200',
        color: 'Negro',
        url: '/img/zapatillas/futbol/mujer/botas-lotto-stadio-200-iii-fg-50.jpg',
        alt: 'Zapatillas Lotto de color negro'
    },
    {
        id: 4,
        persona: 'mujer',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Joma',
        modelo: 'reactive 25',
        color: 'Blanco y azul',
        url: '/img/zapatillas/futbol/mujer/joma_fs_reactive25.jpg',
        alt: 'Zapatillas Joma de color blanco y azul'
    },
    {
        id: 5,
        persona: 'mujer',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Mizuno',
        modelo: 'reactive 25',
        color: 'Azul y blanco',
        url: '/img/zapatillas/futbol/mujer/zapatillas-futbol-mizuno-mrl-sala-club.jpg',
        alt: 'Zapatillas Joma de color azul y blanco'
    },
    {
        id: 6,
        persona: 'niños',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Adidas',
        modelo: 'Predator',
        color: 'Azul, blanco y naranja',
        url: '/img/zapatillas/futbol/niño/adidas-predator.jpg',
        alt: 'Zapatillas Joma de color azul, blanco y naranja'
    },
    {
        id: 7,
        persona: 'niños',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Kappa',
        modelo: 'Player Pro',
        color: 'Plateada',
        url: '/img/zapatillas/futbol/niño/kappa-futbol-sala.jpg',
        alt: 'Zapatillas Kappa de color plata'
    },
    {
        id: 8,
        persona: 'niños',
        categoria: 'futbol',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Nike',
        modelo: 'Phanton',
        color: 'Azul claro',
        url: '/img/zapatillas/futbol/niño/nike-phantom.jpg',
        alt: 'Zapatillas Nike de color azul claro'
    },
    {
        id: 9,
        persona: 'hombre',
        categoria: 'casual',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'DC',
        modelo: 'Court Graffik',
        color: 'Negro',
        url: '/img/zapatillas/casual/hombre/DC-CourtGraffik.jpg',
        alt: 'Zapatillas DC de color negro'
    },
    {
        id: 10,
        persona: 'hombre',
        categoria: 'casual',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'Ecko UnItd',
        modelo: 'Riverside',
        color: 'Blanco y azul',
        url: '/img/zapatillas/casual/hombre/Ecko-UnItd-riverside.jpg',
        alt: 'Zapatillas Ecko UnItd de color blanco y azul'
    },
    {
        id: 11,
        persona: 'hombre',
        categoria: 'casual',
        unidades: 10,
        talla: ['40', '41', '42', '43', '44', '45', '46', '47', '48'],
        marca: 'Emerica',
        modelo: 'Reynolds low',
        color: 'negro',
        url: '/img/zapatillas/casual/hombre/emerica-reynolds-low.jpg',
        alt: 'Zapatillas Emerica de color negro'
    },
    {
        id: 12,
        persona: 'mujer',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Converse',
        modelo: 'All star',
        color: 'Negro',
        url: '/img/zapatillas/casual/mujer/converse-all-star-negras.jpg',
        alt: 'Zapatillas Converse de color negro'
    },
    {
        id: 13,
        persona: 'mujer',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Nike',
        modelo: 'Air Jordan',
        color: 'Rosa, blanco y negro',
        url: '/img/zapatillas/casual/mujer/nike_airjordan.jpg',
        alt: 'Zapatillas Nike de color rosa, blanco y negro'
    },
    {
        id: 14,
        persona: 'mujer',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Zoo york',
        modelo: 'roxbury',
        color: 'Negro',
        url: '/img/zapatillas/casual/mujer/zooyork_roxbury.jpg',
        alt: 'Zapatillas Zoo york de color negro'
    },
    {
        id: 15,
        persona: 'niños',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Adidas',
        modelo: 'Campus',
        color: 'Verde',
        url: '/img/zapatillas/casual/niño/adidas-campus.jpg',
        alt: 'Zapatillas Adidas de color verde'
    },
    {
        id: 16,
        persona: 'niños',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Nike',
        modelo: 'Air Jordan',
        color: 'Marrón',
        url: '/img/zapatillas/casual/niño/nike-air-jordan-1-mocha.jpg',
        alt: 'Zapatillas Nike de color marrón'
    },
    {
        id: 17,
        persona: 'niños',
        categoria: 'casual',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Vans',
        modelo: 'Old Skool',
        color: 'Azul',
        url: '/img/zapatillas/casual/niño/vans-old-skool-v.jpg',
        alt: 'Zapatillas Vans de color azul'
    },
    {
        id: 18,
        persona: 'niños',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Adidas',
        modelo: 'Ultraboost',
        color: 'Azul',
        url: '/img/zapatillas/running/niño/adidas_ultraboost.jpg',
        alt: 'Zapatillas Adidas de color azul'
    },
    {
        id: 19,
        persona: 'niños',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Nike',
        modelo: 'Revolution 7',
        color: 'Blanco, azul y verde',
        url: '/img/zapatillas/running/niño/zapatilla-nike-revolution-7.jpg',
        alt: 'Zapatillas Nike de color blanco, azul y verde'
    },
    {
        id: 20,
        persona: 'niños',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Joma',
        modelo: 'Ultraboost',
        color: 'Negro y naranja',
        url: '/img/zapatillas/running/niño/zapatillas-casual-ferro-22-junior-negro-naranja.jpg',
        alt: 'Zapatillas Joma de color negro y naranja'
    },
    {
        id: 21,
        persona: 'mujer',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Adidas',
        modelo: 'Supernova rise',
        color: 'Blanco, azul y rosa',
        url: '/img/zapatillas/running/mujer/adidas_supernova_rise.jpg',
        alt: 'Zapatillas Adidas de color blanco, azul y rosa'
    },
    {
        id: 22,
        persona: 'mujer',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Joma',
        modelo: 'Speed lady',
        color: 'Azul claro',
        url: '/img/zapatillas/running/mujer/joma_speed_lady_25.jpg',
        alt: 'Zapatillas Joma de color azul claro'
    },
    {
        id: 23,
        persona: 'mujer',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Under armour',
        modelo: 'Turbulence',
        color: 'Rosa',
        url: '/img/zapatillas/running/mujer/under-armour_hovr_turbulence_2.jpg',
        alt: 'Zapatillas Under armour de color rosa'
    },
    {
        id: 24,
        persona: 'hombre',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Nike',
        modelo: 'Revolution 7',
        color: 'Negro',
        url: '/img/zapatillas/running/hombre/DH4071-001-PHCFH001.jpg',
        alt: 'Zapatillas Nike de color negro'
    },
    {
        id: 25,
        persona: 'hombre',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'Joma',
        modelo: 'Speed men',
        color: 'Negro',
        url: '/img/zapatillas/running/hombre/joma-running-speed-men-24-hombre-negro.jpg',
        alt: 'Zapatillas Joma de color negro'
    },
    {
        id: 26,
        persona: 'hombre',
        categoria: 'running',
        unidades: 10,
        talla: ['36', '37', '38', '39', '40', '41', '42', '43'],
        marca: 'On',
        modelo: 'Cloud moster 2',
        color: 'Gris',
        url: '/img/zapatillas/running/hombre/on-cloudmonster-2-running.jpg',
        alt: 'Zapatillas On de color Gris'
    },
];